# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'PortfolioTracker' do
	pod 'Alamofire', '~> 3.1.3'
	pod 'box-ios-sdk-v2', '~> 1.2.2'
	pod 'Gloss', '~> 0.6.1'
	pod 'RealmSwift'
	pod 'Parse'
	pod 'THCalendarDatePicker', '~> 1.2.5'
	
end

